version: "3.8"
services:
  jwt-auth:
    container_name: jwt-auth
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080 #Set the port

      # Database Configuration
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/jwt_auth #Set the schema name
      - SPRING_DATASOURCE_USERNAME=root #Set the username
      - SPRING_DATASOURCE_PASSWORD=root #Set the password
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect #set according to databse

